name: flutter_tools
version: 0.0.38
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.16.0 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.4
  crypto: 0.9.2
  file: ^0.1.0
  http: ^0.11.3
  json_rpc_2: ^2.0.0
  json_schema: ^1.0.3
  linter: ^0.1.17
  mustache4dart: ^1.0.0
  package_config: ^0.1.3
  path: ^1.3.0
  pub_semver: ^1.0.0
  stack_trace: ^1.4.0
  usage: ^2.2.1
  web_socket_channel: ^1.0.0
  xml: ^2.4.1
  yaml: ^2.1.3

  flx:
    path: ../flx

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so here we pin it
  # precisely.
  test: 0.12.13+4

  # Pinned in flutter_test as well.
  analyzer: 0.27.4-alpha.6

dev_dependencies:
  mockito: ^0.11.0

# Exclude this package from the hosted API docs.
dartdoc:
  nodoc: true
