author: Chromium Authors <sky-dev@googlegroups.com>
dependencies:
  args: '>=0.13.0 <1.0.0'
description: Tools for building Sky applications
homepage: https://github.com/domokit/sky_tools
name: sky_tools
version: 0.0.1
