author: Chromium Authors <sky-dev@googlegroups.com>
dependencies:
  args: ^0.13.0
  http_server: ^0.9.5
description: Tools for building Sky applications
homepage: https://github.com/domokit/sky_tools
name: sky_tools
version: 0.0.1
