name: flutter_tools
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.4
  coverage: ^0.9.2
  crypto: '>=1.1.1 <3.0.0'
  file: 2.3.2
  http: ^0.11.3+12
  intl: '>=0.14.0 <0.15.0'
  json_rpc_2: ^2.0.0
  json_schema: 1.0.6
  linter: 0.1.31
  meta: ^1.0.5
  mustache: ^0.2.5
  package_config: '>=0.1.5 <2.0.0'
  platform: 2.0.0
  process: 2.0.3
  quiver: ^0.24.0
  stack_trace: ^1.4.0
  usage: ^3.0.1
  vm_service_client: '0.2.2+4'
  web_socket_channel: ^1.0.4
  xml: ^2.4.1
  yaml: ^2.1.3

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so here we pin it
  # precisely.
  test: 0.12.20

  # Version from the vended Dart SDK as defined in `dependency_overrides`.
  analyzer: any
  front_end: any

dev_dependencies:
  collection: '>=1.9.1 <2.0.0'
  mockito: ^2.0.2

# Exclude this package from the hosted API docs.
dartdoc:
  nodoc: true

dependency_overrides:
  analyzer:
    path: ../../bin/cache/dart-sdk/lib/analyzer
  front_end:
    path: ../../bin/cache/dart-sdk/lib/front_end
  kernel:
    path: ../../bin/cache/dart-sdk/lib/kernel
