os:
  - linux
sudo: false
addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
language: node_js
node_js:
  - "6"
install:
  - ./dev/bots/travis_install.sh
env:
  - SHARD=analyze
  - SHARD=tests
  - SHARD=coverage
  - SHARD=docs
before_script:
  - ./dev/bots/travis_setup.sh
script:
  # TODO(tvolkert): Re-enable `&& ./dev/bots/travis_upload.sh`
  - (./bin/cache/dart-sdk/bin/dart ./dev/bots/test.dart)
cache:
  directories:
    - $HOME/.pub-cache
