name: flutter_gallery
dependencies:
  intl: '>=0.12.4+2 <0.13.0'
  collection: '>=1.4.0 <2.0.0'
  string_scanner: '0.1.4+1'

  flutter:
    path: ../../packages/flutter
  flutter_markdown:
    path: ../../packages/flutter_markdown
  flutter_gallery_assets: '0.0.18'

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
  flutter_driver:
    path: ../../packages/flutter_driver
