name: flutter_gallery
dependencies:
  intl: '>=0.12.4+2 <0.13.0'
  collection: '>=1.4.0 <2.0.0'
  string_scanner: '^0.1.5'

  flutter:
    path: ../../packages/flutter
  flutter_markdown:
    path: ../../packages/flutter_markdown
  # Also update dev/benchmarks/complex_layout/pubspec.yaml
  # and examples/flutter_gallery/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: ea2c9c344c8b6b318341590e2af0707f8a6649f1

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
  flutter_driver:
    path: ../../packages/flutter_driver
