name: flutter_manual_tests
dependencies:
  flutter:
    path: ../../packages/flutter
  flutter_sprites:
    path: ../../packages/flutter_sprites
  flutter_gallery_assets: '0.0.18'

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
