name: flutter_manual_tests
dependencies:
  flutter:
    path: ../../packages/flutter
dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
