name: flutter_manual_tests
dependencies:
  flutter:
    path: ../../packages/flutter
  flutter_sprites:
    path: ../../packages/flutter_sprites
  # Also update dev/manual_tests/pubspec.yaml
  # and dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: 3e55082f0128cb4ef95e0e8d2c14e941024d6da9

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
