name: flutter_manual_tests
dependencies:
  flutter:
    path: ../../packages/flutter
  flutter_sprites:
    path: ../../packages/flutter_sprites
  # Also update dev/manual_tests/pubspec.yaml
  # and dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets: '0.0.21'

dev_dependencies:
  test: any # flutter_test provides the version constraints
  flutter_test:
    path: ../../packages/flutter_test
