name: flutter_unit_tests
dependencies:
  test: ^0.12.5
  quiver: ^0.21.4
  flx:
    path: ../flx
  flutter:
    path: ../flutter
  stocks:
    path: ../../examples/stocks
  # To ensure the version of test doesn't get out of sync.
  flutter_tools:
    path: ../flutter_tools
