name: flutter_analysis_options
author: Flutter Authors <flutter-dev@googlegroups.com>
description: The base and strict analysis options for the Flutter project.
homepage: http://flutter.io

version: 1.0.0
publish_to: none

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.1.0 <3.0.0"

# PUBSPEC CHECKSUM: 0000
