name: material_gallery
dependencies:
  intl: '>=0.12.4+2 <0.13.0'

  flutter:
    path: ../../packages/flutter
  flutter_sprites:
    path: ../../packages/flutter_sprites
  flutter_gallery_assets: '0.0.2'
