name: microbenchmarks
description: A new flutter project.
dependencies:

  # version 0.13.6+1 does not return the value from the command
  # causing flutter tools to always have exit code 0
  # see https://github.com/flutter/flutter/issues/6766
  args: 0.13.6

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  stocks:
    path: ../../../examples/stocks
