name: stocks
dependencies:
  flutter:
    path: ../../packages/flutter
  intl: '>=0.12.4+2 <0.14.0'

dev_dependencies:
  flutter_test:
    path: ../../packages/flutter_test
  flutter_driver:
    path: ../../packages/flutter_driver
