name: complex_layout
description: A new flutter project.

dependencies:
  flutter:
    path: ../../../packages/flutter
  flutter_driver:
    path: ../../../packages/flutter_driver
  # Also update examples/flutter_gallery/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: ef928550119411358b8b25e16aecde6ace513526

dev_dependencies:
  flutter_test:
    path: ../../../packages/flutter_test
