name: complex_layout
description: A new flutter project.

dependencies:
  flutter:
    path: ../../../packages/flutter
  flutter_driver:
    path: ../../../packages/flutter_driver
  # Also update dev/manual_tests/pubspec.yaml
  # and examples/flutter_gallery/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: ea2c9c344c8b6b318341590e2af0707f8a6649f1

dev_dependencies:
  flutter_test:
    path: ../../../packages/flutter_test
