name: integration_ui
description: Flutter non-plugin UI integration tests.

dependencies:
  args: ^0.13.7
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
flutter:
  uses-material-design: true
