name: platform_channel

dependencies:
  args: ^0.13.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    path: ../../packages/flutter_driver

flutter:
  uses-material-design: true
