name: flutter_test
dependencies:
  quiver: ^0.21.4

  # The flutter tools depend on very specific internal implementation
  # details of the 'test' package, which change between versions, so
  # here we pin it precisely to avoid version skew across our packages.
  test: 0.12.15+4

  # We don't actually depend on 'analyzer', but 'test' and 'flutter_tools' do.
  # Like 'flutter_tools', we use the version of the analyzer in the vended Dart
  # SDK as defined in the `dependency_overrides` below.
  analyzer: any

  flutter:
    path: ../flutter

dependency_overrides:
  analyzer:
    path: ../../bin/cache/dart-sdk/lib/analyzer
